air_quality:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: air-quality-and-respiratory
      dataset: air_quality_asthma
      location: EU
      threads: 4
      maximum_bytes_billed: 5000000000   # 5 GB per query

