FROM apache/airflow:2.9.3

RUN pip install --no-cache-dir \
    apache-airflow-providers-google==10.20.0 \
    google-cloud-bigquery==3.25.0 \
    dbt-bigquery==1.8.0 \
    boto3==1.34.0 \
    curl_cffi==0.7.1
